INSERT INTO vaccines (name, age_months, dose_number, funded, description, source_url, sort_order) VALUES
('B型肝炎疫苗 第1劑',     0,  1, true, '出生24小時內接種，預防B型肝炎',                       'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 10),
('B型肝炎疫苗 第2劑',     1,  2, true, '出生滿1個月接種',                                     'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 20),
('五合一疫苗 第1劑',      2,  1, true, '預防白喉、破傷風、百日咳、小兒麻痺、b型嗜血桿菌',     'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 30),
('13價肺炎鏈球菌 第1劑',  2,  1, true, '預防肺炎鏈球菌感染',                                  'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 31),
('五合一疫苗 第2劑',      4,  2, true, '預防白喉、破傷風、百日咳、小兒麻痺、b型嗜血桿菌',     'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 40),
('13價肺炎鏈球菌 第2劑',  4,  2, true, '預防肺炎鏈球菌感染',                                  'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 41),
('卡介苗',                5,  1, true, '預防結核病（滿5個月接種）',                            'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 50),
('五合一疫苗 第3劑',      6,  3, true, '預防白喉、破傷風、百日咳、小兒麻痺、b型嗜血桿菌',     'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 60),
('B型肝炎疫苗 第3劑',     6,  3, true, '出生滿6個月接種',                                     'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 61),
('13價肺炎鏈球菌 追加劑', 12, 3, true, '出生滿12-15個月追加',                                 'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 70),
('MMR三合一疫苗',         12, 1, true, '預防麻疹、腮腺炎、德國麻疹',                          'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 71),
('水痘疫苗',              12, 1, true, '預防水痘',                                            'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 72),
('日本腦炎疫苗 第1劑',    15, 1, true, '預防日本腦炎',                                        'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 73),
('日本腦炎疫苗 第2劑',    15, 2, true, '與第1劑間隔2週',                                      'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 74),
('五合一疫苗 第4劑',      18, 4, true, '出生滿18個月追加',                                    'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 80),
('A型肝炎疫苗 第1劑',     18, 1, true, '114年起新增，出生滿18個月接種',                       'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 81),
('A型肝炎疫苗 第2劑',     27, 2, true, '與第1劑間隔9個月',                                    'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 82),
('日本腦炎追加劑',        60, 3, true, '滿5歲入小學前追加',                                   'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 90),
('DTaP-IPV',              60, 1, true, '入小學前追加，預防白喉、破傷風、百日咳、小兒麻痺',     'https://www.cdc.gov.tw/Category/Page/TxRW-x3WzvPhvEtxM628GA', 91);
